feat(CO-46): GET /dungeon (dungeon instance)
green-fox-academy/chama-olivine-backend pull request #19
Opened 2020-01-16 08:56 UTC by rrtoth

2020-01-16 12:14 UTC, gbr88 submitted a review, later dismissed

2020-01-16 15:18 UTC, juhaszPeterDev commented on src/services/dungeonService.js
> +    }).then(async (res) => {
why do you need async in here?

2020-01-16 15:55 UTC, rrtoth commented on src/services/dungeonService.js
> +    }).then(async (res) => {
accidentally left it there, now removed

2020-01-17 12:31 UTC, gbr88 submitted a review, later dismissed

2020-01-17 13:41 UTC, matyaspeterfi requested changes

2020-01-17 13:41 UTC, matyaspeterfi commented on src/services/dungeonService.js
> +      const dungeon = await this.getDungeonData(res.dungeonId); // 5
left a comment :(

2020-01-17 13:42 UTC, rrtoth commented on src/services/dungeonService.js
> +      const dungeon = await this.getDungeonData(res.dungeonId); // 5
deleted

2020-01-17 13:45 UTC, matyaspeterfi submitted a review, later dismissed

2020-01-17 15:39 UTC, juhaszPeterDev approved these changes

2020-01-17 15:39 UTC, merged